import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource


def generate_launch_description():
    # Define package share directories for nav2_bringup and this package
    nav2_bringup_dir = get_package_share_directory('nav2_bringup')
    pkg_dir = get_package_share_directory('lab6_navigation')

    # Absolute path to the pre-built occupancy grid map (generated by SLAM Toolbox)
    map_yaml_file = os.path.join(pkg_dir, 'maps', 'my_world_map.yaml')

    # Absolute path to the customised Nav2 parameter file.
    # inflation_radius has been increased to 0.55 m to force the global/local
    # planners to keep the robot well away from walls and obstacles.
    nav2_params_file = os.path.join(pkg_dir, 'config', 'nav2_params.yaml')

    # Delegate the full Nav2 stack startup to the upstream bringup_launch.py,
    # injecting our map and parameter overrides via launch arguments.
    nav2_bringup_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(nav2_bringup_dir, 'launch', 'bringup_launch.py')
        ),
        launch_arguments={
            'map': map_yaml_file,
            'params_file': nav2_params_file,
            # use_sim_time=true is critical for synchronising Nav2 with
            # the Gazebo Harmonic simulation clock published on /clock
            'use_sim_time': 'true',
        }.items(),
    )

    return LaunchDescription([
        nav2_bringup_launch,
    ])
